import * as React from 'react';
import CssBaseline from '@mui/material/CssBaseline';
import Paper from '@mui/material/Paper';
import List from '@mui/material/List';
import ListItemAvatar from '@mui/material/ListItemAvatar';
import ListItemText from '@mui/material/ListItemText';
import { ListItemButton } from '@mui/material';

const messages = [
    {
        id: 1,
        primary: 'BrunchI am try out this new BBQ recipe, I think this might be amazing this week?',
        secondary: "I'll be in the neighbourhood this week. Let's grab a bite to eat",
        person: '/static/images/avatar/5.jpg',
    },
    {
        id: 2,
        primary: 'BirthI am try out this new BBQ recipe, I think this might be amazingday Gift',
        secondary: `Do you have a suggestion for a good present for John on his work
      anniversary. I am really confused & would love your thoughts on it.`,
        person: '/static/images/avatar/1.jpg',
    },
    {
        id: 3,
        primary: 'I am try out this new BBQ recipe, I think this might be amazing',
        secondary: 'I am try out this new BBQ recipe, I think this might be amazing',
        person: '/static/images/avatar/2.jpg',
    },
    {
        id: 4,
        primary: 'YeI am try out this new BBQ recipe, I think this might be amazings!',
        secondary: 'I have the tickets to the ReactConf for this year.',
        person: '/static/images/avatar/3.jpg',
    },
    {
        id: 5,
        primary: "Doctor's Appointment",
        secondary: 'My appointment for the doctor was rescheduled for next Saturday.',
        person: '/static/images/avatar/4.jpg',
    },
    {
        id: 6,
        primary: 'Discussion',
        secondary: `Menus that are generated by the bottom app bar (such as a bottom
      navigation drawer or overflow menu) open as bottom sheets at a higher elevation
      than the bar.`,
        person: '/static/images/avatar/5.jpg',
    },
    {
        id: 7,
        primary: 'Summer BBQ',
        secondary: `Who wants to have a cookout this weekend? I just got some furniture
      for my backyard and would love to fire up the grill.`,
        person: '/static/images/avatar/1.jpg',
    },
];

export default function BottomAppBar() {
    return (
        <React.Fragment>
            <CssBaseline />
            <Paper square elevation='0' sx={{
                pb: '50px', height: '200px', overflowY: 'scroll', borderColor: '#4caf50'
            }} variant="outlined" component='div'>
                <List sx={{ mb: 2, borderStyle: 'none' }} component='div'>
                    {messages.map(({ id, primary, secondary, person }) => (
                        <React.Fragment key={id}>
                            <ListItemButton dense='true' divider>
                                <ListItemAvatar>
                                    {/* <Avatar alt="Profile Picture" src={person} /> */}
                                    {id}
                                </ListItemAvatar>
                                <ListItemText primary={primary} />
                            </ListItemButton>
                        </React.Fragment>
                    ))}
                </List>
            </Paper>
        </React.Fragment >
    );
}
