name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  test:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        go: [ 1.15.x, 1.16.x ]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}

    - name: Go Env
      run: |
        go env

    - name: Test
      run: |
        go test -v -race -cover ./...

    - name: Autobahn
      if: >-
        startsWith(matrix.os, 'ubuntu')
      env:
        CRYPTOGRAPHY_ALLOW_OPENSSL_102: yes
      run: |
        make test autobahn

    - name: Autobahn Report Artifact
      if: >-
        startsWith(matrix.os, 'ubuntu')
      uses: actions/upload-artifact@v2
      with:
        name: autobahn report ${{ matrix.go }} ${{ matrix.os }}
        path: autobahn/report
        retention-days: 7
