version: '3.9'

services:
  swagger-editor:
    image: swaggerapi/swagger-editor
    container_name: "swagger-editor"
    ports:
      - "8001:8080"
    volumes:
      - ./api/swagger.yaml:/swagger.yaml

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: "swagger-ui"
    ports:
      - "8002:8080"
    volumes:
      - ./api/swagger.yaml:/swagger.yaml
    environment:
      SWAGGER_JSON: /swagger.yaml

  swagger-api:
    image: stoplight/prism:latest
    container_name: "swagger-api"
    ports:
      - "8003:4010"
    command: mock -h 0.0.0.0 /swagger.yaml
    volumes:
      - ./api/swagger.yaml:/swagger.yaml